/** Declares a capability this agent can handle. */
export interface Capability {
  name: string;
  version: string;
  description?: string;
  parameters?: Record<string, string>;
}

/** Configuration passed to the BaranAgent constructor. */
export interface AgentConfig {
  name: string;
  agentType: string;
  version: string;
  /** Default: http://localhost:9090 */
  sidecarUrl?: string;
  token: string;
  capabilities?: Capability[];
  labels?: Record<string, string>;
  /** Optional fixed agent ID (UUID v7 recommended). Generated by sidecar if omitted. */
  agentId?: string;
}

/** Options for publishing an event. */
export interface PublishOptions {
  eventType: string;
  payload: Record<string, unknown>;
  targetAgent?: string;
  workflowId?: string;
  correlationId?: string;
  metadata?: Record<string, string>;
}
